// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // TODO: Web is currently configured for old project (liora-56689).
      // Run `flutterfire configure` to update.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // TODO: iOS is currently configured for old project (liora-56689).
        // Run `flutterfire configure` to update.
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // TODO: Windows is currently configured for old project (liora-56689).
        // Run `flutterfire configure` to update.
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHqLJNCK16BpokSc0m83cZNrfRmOqMKE', // OLD
    appId: '1:857182781873:web:ef60fe0b9ce60c1d21bd90',
    messagingSenderId: '857182781873',
    projectId: 'liora-56689',
    authDomain: 'liora-56689.firebaseapp.com',
    storageBucket: 'liora-56689.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFhAcg6mAXH-6PlGy3IVp6bClKsDkjv8Q', // ✅ NEW (liora-1e2ea)
    appId: '1:355378586759:android:533dcc856478c05b058422', // ✅ NEW
    messagingSenderId: '355378586759', // ✅ NEW
    projectId: 'liora-1e2ea', // ✅ NEW
    storageBucket: 'liora-1e2ea.firebasestorage.app', // ✅ NEW
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYNWekDPfDMy8tl8MpxTCQilt14zL9dvM', // OLD
    appId: '1:857182781873:ios:e2c080ca3e3b79b021bd90',
    messagingSenderId: '857182781873',
    projectId: 'liora-56689',
    storageBucket: 'liora-56689.firebasestorage.app',
    iosBundleId: 'com.example.lioraa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYNWekDPfDMy8tl8MpxTCQilt14zL9dvM', // OLD
    appId: '1:857182781873:ios:e2c080ca3e3b79b021bd90',
    messagingSenderId: '857182781873',
    projectId: 'liora-56689',
    storageBucket: 'liora-56689.firebasestorage.app',
    iosBundleId: 'com.example.lioraa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHqLJNCK16BpokSc0m83cZNrfRmOqMKE', // OLD
    appId: '1:857182781873:web:1409310dfd3761d621bd90',
    messagingSenderId: '857182781873',
    projectId: 'liora-56689',
    authDomain: 'liora-56689.firebaseapp.com',
    storageBucket: 'liora-56689.firebasestorage.app',
  );
}
